development:
  adapter: postgresql
  encoding: utf8
  database: livechat_development
  pool: 5
  username: alyssa
  password: ""
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: livechat_test
  pool: 5
  username: alyssa
  password: ""
  host: localhost

